[package]
name = "gratitude_box"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
axum = "0.7.4"
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0.111"
serde = { version = "1.0.195", features = ["derive"] }
tokio = { version = "1.35.1", features = ["full"] }

# Logging
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
