[package]
name = "slackify"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_builder = "0.20"
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.35", features = ["full"] }
thiserror = "1.0"
